services:

  db:
    image:
      postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: support_db
    networks:
      - support_network
    container_name: postgres_db

  web_service:
    image:
      likosik/web_service:latest
    ports:
      - "5000:5000"
    networks:
      - support_network
    depends_on:
      - db
    container_name: web_service
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - support_network
    depends_on:
      - web_service
  
    
  

networks:
  support_network:
    driver: bridge

volumes:
  pgdata:
